# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"G\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tpassword2\x18\x03 \x01(\t\"3\n\x10LoginUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\"\n\x11UserTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x10GetUserIdRequest\x12\r\n\x05token\x18\x01 \x01(\t\"!\n\x11GetUserIdResponse\x12\x0c\n\x04user\x18\x01 \x01(\x03\x32\xc9\x01\n\x0b\x41uthService\x12>\n\nCreateUser\x12\x17.auth.CreateUserRequest\x1a\x17.auth.UserTokenResponse\x12<\n\tLoginUser\x12\x16.auth.LoginUserRequest\x1a\x17.auth.UserTokenResponse\x12<\n\tGetUserId\x12\x16.auth.GetUserIdRequest\x1a\x17.auth.GetUserIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=20
  _globals['_CREATEUSERREQUEST']._serialized_end=91
  _globals['_LOGINUSERREQUEST']._serialized_start=93
  _globals['_LOGINUSERREQUEST']._serialized_end=144
  _globals['_USERTOKENRESPONSE']._serialized_start=146
  _globals['_USERTOKENRESPONSE']._serialized_end=180
  _globals['_GETUSERIDREQUEST']._serialized_start=182
  _globals['_GETUSERIDREQUEST']._serialized_end=215
  _globals['_GETUSERIDRESPONSE']._serialized_start=217
  _globals['_GETUSERIDRESPONSE']._serialized_end=250
  _globals['_AUTHSERVICE']._serialized_start=253
  _globals['_AUTHSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
